name: cce-fe
canonical: 111-cce-fe
author: NIDHI BHATNAGAR
description: cce-fe
type: stack
image: ""
keywords:
- ccefe
- provider:flexibleengine
- provider:vault
technologies:
- technology: stackcraft
  version: "1"
config:
  pipeline:
    pipeline:
      path: pipeline/terraform-pipeline.yaml
    variables:
      path: pipeline/variables.sample.yaml
  terraform:
    111-cce-fe:
      destination: ($ project $)/terraform/($ environment $)/111-cce-fe.tf
      path: terraform/111-cce-fe.tf.sample
