name: ccenodes
canonical: 111-ccenodes
author: NIDHI BHATNAGAR
description: ccenodes
type: stack
image: ""
keywords:
- ccenodes
- provider:flexibleengine
- provider:vault
technologies:
- technology: stackcraft
  version: "1"
config:
  pipeline:
    pipeline:
      path: pipeline/terraform-pipeline.yaml
    variables:
      path: pipeline/variables.sample.yaml
  terraform:
    111-ccenodes:
      destination: ($ project $)/terraform/($ environment $)/111-ccenodes.tf
      path: terraform/111-ccenodes.tf.sample
