name: FE_Stackcraft_nidhi
canonical: 111-fe_stackcraft_nidhi
author: NIDHI BHATNAGAR
description: FE_Stackcraft_nidhi
type: stack
image: ""
keywords:
- demo
- provider:flexibleengine
- provider:vault
technologies: []
config:
  terraform:
    111-fe_stackcraft_nidhi:
      destination: ($ project $)/terraform/($ environment $)/111-fe_stackcraft_nidhi.tf
      path: terraform/111-fe_stackcraft_nidhi.tf.sample
