version: "2"
name: FE_Stackcraft_nidhi
canonical: 111-fe_stackcraft_nidhi
author: NIDHI BHATNAGAR
status: private
description: FE_Stackcraft_nidhi
image: ""
keywords:
- demo
- provider:flexibleengine
- provider:vault
technologies:
- technology: stackcraft
  version: "1"
dependencies: []
config:
  default:
    description: ""
    name: default
    terraform:
      111-fe_stackcraft_nidhi:
        destination: ($ project $)/terraform/($ environment $)/111-fe_stackcraft_nidhi.tf
        path: terraform/111-fe_stackcraft_nidhi.tf.sample
